version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: medical_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped